### ISSUE TITLE
Unable to start service com.asterinet.react.bgactions.RNBackgroundActionsTask@7cf005d with Intent

### ISSUE THREAD

**Issue by saim683** [Rapsssito/react-native-background-actions#237]
java.lang.RuntimeException: Unable to start service com.asterinet.react.bgactions.RNBackgroundActionsTask@7cf005d with Intent
                 { cmp=com.officermetrics/com.asterinet.react.bgactions.RNBackgroundActionsTask (has extras) }: java.lang.IllegalArgumentException: Cannot set
                 both FLAG_IMMUTABLE and FLAG_MUTABLE for PendingIntent
                 
I am using the latest version of react-native-background-actions. But when my app start's after 10 seconds my app goes to crash. I am using android 14.

**Comment by RitheanyFT** [comment]
🎉 This issue has been resolved in version 4.0.0 🎉

https://github.com/Rapsssito/react-native-background-actions/issues/200#issuecomment-2172709359

**Comment by ctTushar** [comment]
still issue persist

**Comment by saim683** [comment]
It's working now. Thanks

**Comment by vishalyad16** [comment]
@ctTushar @saim683 @RitheanyFT @gasolin 

I am still experiencing crashes while sharing my screen, and this has been happening for the past four weeks. How can I resolve this issue? Please help.
1)
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.asterinet.react.bgactions">
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_DATA_SYNC" />
    <application>
        <service android:name=".RNBackgroundActionsTask" android:foregroundServiceType="dataSync"/>
    </application>
</manifest>

2)RNBackgroundTask.java

final PendingIntent contentIntent;
        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
            contentIntent = PendingIntent.getActivity(context,0, notificationIntent, PendingIntent.FLAG_MUTABLE | 
            PendingIntent.FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT);
        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_MUTABLE);
        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT | 
            PendingIntent.FLAG_IMMUTABLE);
        } else {
            contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT);
        }
        
3)
handleAppStateChange = async (nextAppState) => {
    if (nextAppState === 'active') {
      isPipOpen=true;
      console.log('videoAgora', 'ForeGround');
      clearInterval(this.intervalReset);
      clearInterval(this.intervalBackground);
     //this.restartTranslationRecognition('User Reset');
      await BackgroundService.stop();
    this.resetTimer();
    }
    else{
      clearInterval(this.intervalReset);
      console.log('videoAgora', 'BackgroundStart');
      BackgroundService.stop();
      BackgroundService.start(this.veryIntensiveTask, this.options);
      try{
        // if (isPipOpen) {
        //   PipHandler.enterPipMode(300, 214);
        //   isPipOpen=false;
        // }
      }
      catch(error){
      }
    }
    this.setState({appState: nextAppState});
    // console.log('state', nextAppState);
  };
        
  "react-native-background-actions": "^4.0.0",

**Comment by vishalyad16** [comment]
@ctTushar @saim683 @RitheanyFT @gasolin 

I am still experiencing crashes while sharing my screen, and this has been happening for the past four weeks. How can I resolve this issue? Please help.

~<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.asterinet.react.bgactions">
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_DATA_SYNC" />
    <application>
        <service android:name=".RNBackgroundActionsTask" android:foregroundServiceType="dataSync"/>
    </application>
</manifest>`

2)RNBackgroundTask.java
`final PendingIntent contentIntent;
        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
            contentIntent = PendingIntent.getActivity(context,0, notificationIntent, PendingIntent.FLAG_MUTABLE | 
            PendingIntent.FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT);
        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_MUTABLE);
        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT | 
            PendingIntent.FLAG_IMMUTABLE);
        } else {
            contentIntent = PendingIntent.getActivity(context, 0, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT);
        }`
        
3) 
`handleAppStateChange = async (nextAppState) => {
    if (nextAppState === 'active') {
      isPipOpen=true;
      console.log('videoAgora', 'ForeGround');
      clearInterval(this.intervalReset);
      clearInterval(this.intervalBackground);
     //this.restartTranslationRecognition('User Reset');
      await BackgroundService.stop();
    this.resetTimer();
    }
    else{
      clearInterval(this.intervalReset);
      console.log('videoAgora', 'BackgroundStart');
      BackgroundService.stop();
      BackgroundService.start(this.veryIntensiveTask, this.options);
      try{
        // if (isPipOpen) {
        //   PipHandler.enterPipMode(300, 214);
        //   isPipOpen=false;
        // }
      }
      catch(error){
      }
    }
    this.setState({appState: nextAppState});
    // console.log('state', nextAppState);
  };`
        
  "react-native-background-actions": "^4.0.0",

**Comment by vishalyad16** [comment]
@k-lpmg The microphone stops working when the app goes into the background.
please check this https://github.com/Rapsssito/react-native-background-actions/issues/254#issue-2812232276

**Comment by oyepez003** [comment]
If you are using expo you can add a new plugin to update the AndroidManifest.xml

file: withAndroidManifestEdit.js:

```js
const { withAndroidManifest } = require("@expo/config-plugins");

module.exports = function withAndroidManifestEdit(config) {
  return withAndroidManifest(config, async (config) => {
    const androidManifest = config.modResults;

    // Buscar la etiqueta <application>
    const application = androidManifest.manifest.application[0];
    const serviceName = "com.asterinet.react.bgactions.RNBackgroundActionsTask";
    let service = application.service?.find(
      (s) => s["$"]["android:name"] === serviceName,
    );

    if (service) {
      service["$"]["android:foregroundServiceType"] = "dataSync";
    } else {
      application.service = application.service || [];
      application.service.push({
        $: {
          "android:name": serviceName,
          "android:foregroundServiceType": "dataSync",
        },
      });
    }

    return config;
  });
};

```
And now in your app.json:

```json
{
      "plugins": [
      ...
      "./withAndroidManifestEdit"
      ...
    ],
}
```

Finally, create a new build using `eas build` or `expo run android`

You can update the plugin and add all the services your app requires.

**Comment by Rapsssito** [comment]
Probably related fix: https://github.com/Rapsssito/react-native-background-actions/pull/263. Please, check with the latest version 4.1.0, as there has been an overhaul related to action types.
